--- 
title: "dsSurvival: Privacy preserving survival models in DataSHIELD"
author: "Soumya Banerjee and Tom R P Bishop"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a bookdown demonstrating how to build privacy preserving survival models using dsSurvival in DataSHIELD. The output format for this example is bookdown::gitbook."
---

# Prerequisites

Please install R and R Studio. We outline some of the prerequisites that need to be installed below.


```{r eval=FALSE}


install.packages('devtools')

library(devtools)

devtools::install_github('neelsoumya/dsSurvivalClient')

devtools::install_github('datashield/dsBaseClient@6.1.1')

install.packages('rmarkdown')

install.packages('knitr')

install.packages('tinytex')

install.packages('metafor')


```

<!-- Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`. -->

<!-- To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX <https://yihui.org/tinytex/>. -->

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

